---
- name: Prepare baseline setup
  hosts: autodock.cdrl-ut.org
  remote_user: vultr
  become: yes

  roles:
    - role: common
      state: present
    - role: autodock
      state: present
    - role: mgltools
      state: present

