---
name: Deploy Autodock-MGLTools on Vultr

on:
  release:
    type: [published]

jobs:
  infrastructure-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init -no-color
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
  configuration_ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Ansible
        uses: ansible-playbook site.yml



